// eslint-disable-next-line import/prefer-default-export
export const INIT_APP = 'INIT_APP';

export const CREATE_NEW_POLL = 'CREATE_NEW_POLL';

export const LOG_IN_REQUEST = 'LOG_IN_REQUEST';

export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';

export const LOG_IN_FAIL = 'LOG_IN_FAIL';

export const LOG_OUT = 'LOG_OUT';

export const CREATE_POLL_REQUEST = 'CREATE_POLL_REQUEST';

export const CREATE_POLL_SUCCESS = 'CREATE_POLL_SUCCESS';

export const CREATE_POLL_FAIL = 'CREATE_POLL_FAIL';

export const ADD_NEW_POLL = 'ADD_NEW_POLL';

export const SUBMIT_POLL_REQUEST = 'SUBMIT_POLL_REQUEST';

export const SUBMIT_POLL_SUCCESS = 'SUBMIT_POLL_SUCCESS';

export const SUBMIT_POLL_FAIL = 'SUBMIT_POLL_FAIL';

export const ADD_SUBMISSION_REQUEST = 'ADD_SUBMISSION_REQUEST';

export const ADD_SUBMISSION_SUCCESS = 'ADD_SUBMISSION_SUCCESS';

export const ADD_SUBMISSION_FAIL = 'ADD_SUBMISSION_FAIL';

export const UPDATE_POLL_RESULT = 'UPDATE_POLL_RESULT';

export const TAKE_USER_POLLS_REQUEST = 'TAKE_USER_POLLS_REQUEST';

export const TAKE_USER_POLLS_SUCCESS = 'TAKE_USER_POLLS_SUCCESS';

export const TAKE_USER_POLLS_FAIL = 'TAKE_USER_POLLS_FAIL';

export const TAKE_USER_API_KEY = 'TAKE_USER_API_KEY';

export const GET_POLL_REQUEST = 'GET_POLL_REQUEST';

export const GET_POLL_SUCCESS = 'GET_POLL_SUCCESS';

export const GET_POLL_FAIL = 'GET_POLL_FAIL';

export const DELETE_POLL_REQUEST = 'DELETE_POLL_REQUEST';

export const DELETE_POLL_SUCCESS = 'DELETE_POLL_SUCCESS';

export const DELETE_POLL_FAIL = 'DELETE_POLL_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const INIT_SOCKET = 'INIT_SOCKET';

export const UPDATE_RESULT_SOCKET = 'UPDATE_RESULT_SOCKET';
